# Generated by Django 5.1.3 on 2024-11-14 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('ae_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal reference code.', primary_key=True, serialize=False, unique=True, verbose_name='ae_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Item created at.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Item updated at.', verbose_name='Updated At')),
                ('battery_level', models.DecimalField(decimal_places=2, default=0.5, help_text='the % capacity remaining in the battery expressed', max_digits=3, verbose_name='battery_level_percantage')),
                ('is_at_home', models.BooleanField(default=True, help_text='Is this car at home and connected to the grid', verbose_name='car_is_at_home')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ae_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal reference code.', primary_key=True, serialize=False, unique=True, verbose_name='ae_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Item created at.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Item updated at.', verbose_name='Updated At')),
                ('username', models.CharField(blank=True, help_text='Username for the user', max_length=50, verbose_name='Username')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargingSchedule',
            fields=[
                ('ae_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal reference code.', primary_key=True, serialize=False, unique=True, verbose_name='ae_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Item created at.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Item updated at.', verbose_name='Updated At')),
                ('paused_until', models.DateTimeField(help_text='When this schedule is paused until', null=True, verbose_name='charging_schedule_paused_until')),
                ('override_applied_at', models.DateTimeField(help_text='When the charge now button was pressed', null=True, verbose_name='override_applied_at')),
                ('car', models.ForeignKey(help_text='Car linked to Charging Schedule', on_delete=django.db.models.deletion.CASCADE, to='CarChargingScheduler.car', verbose_name='Car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargingSlot',
            fields=[
                ('ae_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal reference code.', primary_key=True, serialize=False, unique=True, verbose_name='ae_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Item created at.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Item updated at.', verbose_name='Updated At')),
                ('start_datetime', models.DateTimeField(help_text='When this charge slot starts', verbose_name='charge_slot_starts_at')),
                ('end_datetime', models.DateTimeField(help_text='When this charge slot ends', verbose_name='charge_slot_ends_at')),
                ('battery_level_gained', models.DecimalField(decimal_places=2, default=0.5, help_text='the percentage point increase in battery level gained via this charging slot', max_digits=3, verbose_name='battery_level_gained')),
                ('charging_schedule', models.ForeignKey(help_text='Charge schedule containing this charge slot', on_delete=django.db.models.deletion.CASCADE, related_name='charging_slots', to='CarChargingScheduler.chargingschedule', verbose_name='Charging Schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(help_text='User this car belongs to', on_delete=django.db.models.deletion.PROTECT, to='CarChargingScheduler.user', verbose_name='User'),
        ),
    ]
